### ISSUE TITLE
Tracing simple Lean4 [no-deps] repo with CONTAINER=native fails

### ISSUE THREAD

**Issue by antonkov** [lean-dojo/LeanDojo#6]
I try to run it with `export CONTAINER=native` since I have arm64 (Macbook Air M2, 2022, 24GB) but provided docker container even though creates multiarch image but based on amd64 image which makes it run at least ~10x slower (I'll try to take a look if I can fix and create an image for arm64)

Tracing example repo works now as it downloads it from cache (I believe I was receiving the same error on example ~2 days ago) , but trying to trace a simple repo with code:

```
from lean_dojo import LeanGitRepo, trace

repo = LeanGitRepo("https://github.com/antonkov/test-extract", "99bd597f4a84117f7eb20750c0ea3c2eaaefa6e4")
trace(repo, dst_dir="traced_test-extract")
```

takes 5-30mins and then fails with 

```2023-07-04 21:56:07.366 | INFO     | lean_dojo.data_extraction.trace:get_traced_repo_path:132 - Tracing LeanGitRepo(url='https://github.com/antonkov/test-extract', commit='99bd597f4a84117f7eb20750c0ea3c2eaaefa6e4')
2023-07-04 21:56:09.259 | INFO     | __main__:main:98 - Building test-extract
2023-07-04 21:56:10.714 | INFO     | __main__:main:131 - Tracing test-extract
0it [00:05, ?it/s]

Traceback (most recent call last):
  File "/Users/antonkovsharov/code/LeanDojo/src/lean_dojo/data_extraction/main.py", line 4, in <module>
    trace(repo, dst_dir="traced_test-extract")
  File "/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/site-packages/lean_dojo/data_extraction/trace.py", line 163, in trace
    cached_path = get_traced_repo_path(repo)
  File "/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/site-packages/lean_dojo/data_extraction/trace.py", line 135, in get_traced_repo_path
    _trace(repo)
  File "/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/site-packages/lean_dojo/data_extraction/trace.py", line 66, in _trace
    _trace_lean4(repo)
  File "/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/site-packages/lean_dojo/data_extraction/trace.py", line 105, in _trace_lean4
    container.run(
  File "/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/site-packages/lean_dojo/container.py", line 191, in run
    self._unmount_files(mounts)
  File "/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/site-packages/lean_dojo/container.py", line 153, in _unmount_files
    path.rmdir()
  File "/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/pathlib.py", line 1215, in rmdir
    self._accessor.rmdir(self)
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/3s/0f7yjj3j6q1f3cq15qkp554r0000gn/T/tmpbvutds_0/workspace/test-extract'```

**Comment by lakesare** [comment]
A possibly related issue - when I try to run the Lean 4 demo from the docs (https://leandojo.readthedocs.io/en/latest/getting-started.html#extracting-data-from-lean-4), it runs for at least 1 hour, likely for much longer (this is the state I copypasted at 1 hour past starting the script).

```
2023-07-03 22:03:43.791 | INFO     | lean_dojo.data_extraction.trace:get_traced_repo_path:132 - Tracing LeanGitRepo(url='https://github.com/yangky11/lean4-example', commit='805b3ad26fd1e6c8ba507f41ab289ec19c0efe2c')
2023-07-03 17:03:53.576 | INFO     | __main__:main:98 - Building lean4-example
info: syncing channel updates for 'nightly'
info: latest update on nightly, lean version nightly-2023-07-02
info: downloading component 'lean'
info: installing component 'lean'
info: cloning https://github.com/leanprover-community/mathlib4.git to ./lake-packages/mathlib
info: cloning https://github.com/leanprover/std4 to ./lake-packages/std
info: cloning https://github.com/gebner/quote4 to ./lake-packages/Qq
info: cloning https://github.com/JLimperg/aesop to ./lake-packages/aesop
[0/4] Building Lean4Example
[1/4] Compiling Lean4Example
[1/4] Building Main
[3/4] Compiling Main
[4/4] Linking lean4-example
2023-07-03 17:13:56.501 | INFO     | __main__:main:131 - Tracing lean4-example

  0%|          | 0/2 [00:00<?, ?it/s]
  0%|          | 0/2 [00:05<?, ?it/s]
  0%|          | 0/2 [00:10<?, ?it/s]
  0%|          | 0/2 [00:14<?, ?it/s]
  0%|          | 0/2 [00:19<?, ?it/s]
  0%|          | 0/2 [00:25<?, ?it/s]
  0%|          | 0/2 [00:30<?, ?it/s]
  0%|          | 0/2 [00:35<?, ?it/s]
  0%|          | 0/2 [00:40<?, ?it/s]
  0%|          | 0/2 [00:45<?, ?it/s]
  0%|          | 0/2 [00:50<?, ?it/s]
  0%|          | 0/2 [00:55<?, ?it/s]
  0%|          | 0/2 [01:00<?, ?it/s]
  0%|          | 0/2 [01:05<?, ?it/s]
  0%|          | 0/2 [01:10<?, ?it/s]
  0%|          | 0/2 [01:15<?, ?it/s]
  0%|          | 0/2 [01:20<?, ?it/s]
  0%|          | 0/2 [01:25<?, ?it/s]
  0%|          | 0/2 [01:30<?, ?it/s]
  0%|          | 0/2 [01:35<?, ?it/s]
  0%|          | 0/2 [01:40<?, ?it/s]
  0%|          | 0/2 [01:45<?, ?it/s]
  0%|          | 0/2 [01:50<?, ?it/s]
  0%|          | 0/2 [01:55<?, ?it/s]
  0%|          | 0/2 [02:00<?, ?it/s]
  0%|          | 0/2 [02:05<?, ?it/s]
  0%|          | 0/2 [02:10<?, ?it/s]
  0%|          | 0/2 [02:15<?, ?it/s]
  0%|          | 0/2 [02:20<?, ?it/s]
  0%|          | 0/2 [02:25<?, ?it/s]
  0%|          | 0/2 [02:30<?, ?it/s]
  0%|          | 0/2 [02:35<?, ?it/s]
  0%|          | 0/2 [02:40<?, ?it/s]
  0%|          | 0/2 [02:45<?, ?it/s]
  0%|          | 0/2 [02:50<?, ?it/s]
  0%|          | 0/2 [02:56<?, ?it/s]
  0%|          | 0/2 [03:01<?, ?it/s]
  0%|          | 0/2 [03:06<?, ?it/s]
  0%|          | 0/2 [03:11<?, ?it/s]
  0%|          | 0/2 [03:16<?, ?it/s]
  0%|          | 0/2 [03:21<?, ?it/s]

100%|██████████| 2/2 [03:26<00:00,  2.50s/it]
100%|██████████| 2/2 [03:26<00:00, 103.02s/it]
```

My mac:

```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,4
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2,2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	430.120.6.0.0
  OS Loader Version:	540.120.3~6
  SMC Version (system):	2.29f24
  Serial Number (system):	C02TV3S9G8WN
  Hardware UUID:	AD3552D6-631B-5028-B9F7-F258A43BE170
  Provisioning UDID:	AD3552D6-631B-5028-B9F7-F258A43BE170
```

**Comment by yangky11** [comment]
Hi Anton,

I was able to reproduce this error on my Intel Mac and fixed it in the [dev](https://github.com/lean-dojo/LeanDojo/tree/dev) branch. Could you please try the updated code and see if it works? I'm running some tests and will update the main branch later.

**Comment by yangky11** [comment]
merged into main

**Comment by antonkov** [comment]
Parsing succeeded in ~10mins this time, Thanks for the quick fix.

```
python main.py         
2023-07-05 19:14:53.508 | INFO     | lean_dojo.data_extraction.trace:get_traced_repo_path:132 - Tracing LeanGitRepo(url='https://github.com/antonkov/test-extract', commit='99bd597f4a84117f7eb20750c0ea3c2eaaefa6e4')
2023-07-05 19:14:55.675 | INFO     | __main__:main:102 - Building test-extract
2023-07-05 19:14:57.506 | INFO     | __main__:main:135 - Tracing test-extract
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 616/716 [07:15<01:14,  1.35it/s]/Users/antonkovsharov/miniconda3/envs/ReProver/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
2023-07-05 19:22:18,917 INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 618/618 [00:27<00:00, 22.21it/s]
2023-07-05 19:22:53,005 INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 618/618 [00:06<00:00, 102.59it/s]
2023-07-05 19:23:05.652 | INFO     | lean_dojo.data_extraction.trace:trace:164 - Loading the traced repo from /Users/antonkovsharov/.cache/lean_dojo/antonkov-test-extract-99bd597f4a84117f7eb20750c0ea3c2eaaefa6e4/test-extract
2023-07-05 19:23:07,275 INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 618/618 [00:33<00:00, 18.40it/s]
```

However consecutive runs (if I just change one file) still run ~618 steps for around 10mins. I'm curious what those steps are. Will be nice to see more information in logs. What is the supposed iteration workflow to work on tracer logic? Reparsing from git repo takes ~10 mins which is too long for an iterative development. Let me know if I'm missing something

**Comment by antonkov** [comment]
Oh, I actually didn't get any `build` folder generated with `ast.json` and `trace.xml`. 
```
ls traced_test-extract 
test-extract
(ReProver) ➜  LeanDojo git:(main) ✗ ls traced_test-extract/test-extract 
ExtractData.lean TestExtract.lean lake-packages    lakefile.lean    lean-toolchain
```

**Comment by yangky11** [comment]
The time-consuming part is tracing the dependencies `lake-packages/lean4`. If you run `ls -lR traced_test-extract/test-extract | grep "\.ast\.json"`, you'll see 618 `.ast.json` files. Maybe a solution is to make it configurable whether the dependencies should be traced?

I'm not sure why `./TestExtract.lean` is not traced, checking it right now...

**Comment by antonkov** [comment]
Yeah - good idea. Should it be one more argument to trace(repo, dst_dir, with_deps) and then in cache it's stored keyed by a triple cache.get(repo.url, repo.commit, with_deps)? Let me know if you have another interface in mind - I can try to do that tomorrow to familiarize myself a bit more with the codebase

**Comment by yangky11** [comment]
An `with_deps: bool = True` parameter for `trace` sounds great. Do we need to save repos without dependencies to the cache if they are mostly for debugging?

**Comment by yangky11** [comment]
I just fixed the problem with `./TestExtract.lean` in [this pull request](https://github.com/lean-dojo/LeanDojo/pull/8).

**Comment by antonkov** [comment]
yup, good point, as a first step we can definitely skip cache for `with_deps = False`. I'll give it a go tmr

**Comment by yangky11** [comment]
thx!

**Comment by antonkov** [comment]
I needed to mark default_target https://github.com/antonkov/test-extract/commit/8e4850b7be9474e5fa81a91352cd8e4b2860aa3e
but it worked now - thanks
