### ISSUE TITLE
Leandojo didn't trace newly created .lean file 

### ISSUE THREAD

**Issue by chenyang-an** [lean-dojo/LeanDojo#91]
I'm using the trace function of Leandojo. The code is as follows:

```
from lean_dojo import LeanGitRepo, trace

repo = LeanGitRepo("https://github.com/yangky11/lean4-example", "7d711f6da4584ecb7d4f057715e1f72ba175c910")
trace(repo, dst_dir="traced_lean4-example")

```
This works just fine.

However, then I created a new .lean file in the directory of lean4-example and then uploaded everything to Github. Leandojo didn't trace the new .lean file for me. Locally on my own machine, every theorems in the newly created .lean can be compiled by the Lean4 compiler.

I'm not sure why is this problem happening. I do notice that in build/ir directory there is no .trace or olean file for my newly created .lean file.

Do you know why this is happening? Thanks!

**Comment by yangky11** [comment]
Hi,

Did you push the new file to a GitHub repo? Can you point me to the repo?

**Comment by chenyang-an** [comment]
The GitHub link is https://github.com/chenyang-an/lean4_example_test with commit number 0454bbe5855cfbebf840db2868f8d10cab0d6a2e.

I directly use the Lean 4 toy example code and one more .lean file to it.

Here is the tracing code: 
from lean_dojo import LeanGitRepo, trace

```
repo = LeanGitRepo("https://github.com/chenyang-an/lean4_example_test","0454bbe5855cfbebf840db2868f8d10cab0d6a2e")
traced_repo = trace(repo)
data = []

print(traced_repo.num_traced_files)
print(traced_repo.get_traced_file('Lean4Example.lean').get_traced_theorems())

print(traced_repo.get_traced_file('Lean4Example_1.lean').get_traced_theorems())
```

Here is the error
```
python load_data.py
、2023-11-04 16:13:54.894 | INFO     | lean_dojo.data_extraction.trace:trace:174 - Loading the traced repo from /home/chenyang/.cache/lean_dojo/chenyang-an-lean4_example_test-0454bbe5855cfbebf840db2868f8d10cab0d6a2e/lean4_example_test
2023-11-04 16:13:57,076	INFO worker.py:1633 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
 30%|████████████▏                            | 184/620 [00:08<00:13, 31.41it/s](raylet) [2023-11-04 16:14:06,983 E 1959119 1959134] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2023-11-04_16-13-55_357538_1958868 is over 95% full, available space: 337906065408; capacity: 15228501098496. Object creation will fail if spilling is required.
 75%|██████████████████████████████▌          | 462/620 [00:16<00:02, 57.96it/s](raylet) [2023-11-04 16:14:16,988 E 1959119 1959134] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2023-11-04_16-13-55_357538_1958868 is over 95% full, available space: 337906036736; capacity: 15228501098496. Object creation will fail if spilling is required.
100%|█████████████████████████████████████████| 620/620 [00:23<00:00, 25.95it/s]
620
[TracedTheorem(theorem=Theorem(repo=LeanGitRepo(url='https://github.com/chenyang-an/lean4_example_test', commit='0454bbe5855cfbebf840db2868f8d10cab0d6a2e'), file_path=PosixPath('Lean4Example.lean'), full_name='hello_world')), TracedTheorem(theorem=Theorem(repo=LeanGitRepo(url='https://github.com/chenyang-an/lean4_example_test', commit='0454bbe5855cfbebf840db2868f8d10cab0d6a2e'), file_path=PosixPath('Lean4Example.lean'), full_name='foo'))]
Traceback (most recent call last):
  File "/home/chenyang/leandojo_project/proplogic/load_data.py", line 11, in <module>
    print(traced_repo.get_traced_file('Lean4Example_1.lean').get_traced_theorems())
  File "/data/chenyang/anaconda3/envs/atpself/lib/python3.10/site-packages/lean_dojo/data_extraction/traced_data.py", line 1474, in get_traced_file
    return self.traced_files_graph.nodes[str(path)]["traced_file"]
  File "/data/chenyang/anaconda3/envs/atpself/lib/python3.10/site-packages/networkx/classes/reportviews.py", line 194, in __getitem__
    return self._nodes[n]
KeyError: 'Lean4Example_1.lean'
```

Thanks!

**Comment by yangky11** [comment]
This is probably because Lean4Example_1.lean is not actually used by the project. If you run `lake build`, you wouldn't find it in the "./build" directory.

**Comment by chenyang-an** [comment]
I see. But why is the file Lean4Example_1.lean not able to be traced by leandojo? ./build is not uploaded so I guess it's not the problem.

**Comment by yangky11** [comment]
LeanDojo only traces files that are actually used

**Comment by chenyang-an** [comment]
I see. Thanks!

**Comment by Xuekai-Zhu** [comment]
Hi, I meet the same proplem, and i want to ask a follow-up question:
I use following code will obtain am keyerror: `KeyError: 'Mathlib/Data/Relqk2dq38z.lean'`
How can I add these missing files to LeanDojo? 
Or how can I avoid this issue during the use of LeanDojo?



```
from lean_dojo import *
from proof_flow.src.utils import prepare_environment_for_lean_dojo, repo_root

prepare_environment_for_lean_dojo()

#command: /home/zhuxuekai/.elan/bin/lake
# args: [b'/home/zhuxuekai/.elan/bin/lake', b'env', b'lean', b'--threads=1', b'--memory=32768', b'Mathlib/Data/Relqk2dq38z.lean']
#

cached_path = os.path.expanduser(
    "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/.cache/lean_dojo/leanprover-community-mathlib4-29dcec074de168ac2bf835a77ef68bbe069194c5/mathlib4")
# repo = LeanGitRepo.from_path(cached_path)

build_deps = True
# cached_path = get_traced_repo_path(repo, build_deps)
# logger.info(f"Loading the traced repo from {cached_path}")
traced_repo = TracedRepo.load_from_disk(cached_path, build_deps)
traced_repo.check_sanity()

print("traced_files_graph", traced_repo.traced_files_graph)
print("traced_files", len(traced_repo.traced_files))

print("-----------------------")

traced_file = traced_repo.get_traced_file("Mathlib/Data/Relqk2dq38z.lean")
print(traced_file)
```

**Comment by Xuekai-Zhu** [comment]
Huge thanks for your quick reply, the following is a minimal example to reproduce the problem using the latest main branch of LeanDojo (v2.2.0).

output: `KeyError: 'Mathlib/Data/Relqk2dq38z.lean'`

```
from lean_dojo import *

# my local cache : lean_dojo/leanprover-community-mathlib4-29dcec074de168ac2bf835a77ef68bbe069194c5/mathlib4
# also equal to : 
# repo = LeanGitRepo(
#     "https://github.com/leanprover-community/mathlib4",
#     "29dcec074de168ac2bf835a77ef68bbe069194c5",
# )
# traced_repo = trace(repo)

cached_path = os.path.expanduser(
    "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/.cache/lean_dojo/leanprover-community-mathlib4-29dcec074de168ac2bf835a77ef68bbe069194c5/mathlib4")

build_deps = True
traced_repo = TracedRepo.load_from_disk(cached_path, build_deps)

traced_file = traced_repo.get_traced_file("Mathlib/Algebra/ContinuedFractions/Translations2qx3rbck.lean")
print(traced_file)
```

**Comment by yangky11** [comment]
I cannot run this example due to `/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/.cache/lean_dojo/leanprover-community-mathlib4-29dcec074de168ac2bf835a77ef68bbe069194c5/mathlib4`

**Comment by Xuekai-Zhu** [comment]
Thank you for your checking. 
I provide more concise sample as follow:

`output: KeyError: 'Mathlib/Data/Relqk2dq38z.lean'`

```
from lean_dojo import *
repo = LeanGitRepo(
    "https://github.com/leanprover-community/mathlib4",
    "29dcec074de168ac2bf835a77ef68bbe069194c5", )
traced_repo = trace(repo)

traced_file = traced_repo.get_traced_file("Mathlib/Algebra/ContinuedFractions/Translations2qx3rbck.lean")
print(traced_file)
```

**Comment by Xuekai-Zhu** [comment]
I finally solved this bug by:
**remove all dependencies installed before.**
Then:
```
1. install elan
2. install leandojo from main branch
3. the eof error disappear.
```

Thank @yangky11  very much for your quick reply!

**Comment by yangky11** [comment]
Great. I'll mark this issue as resolved.
